document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'UTF-8\'><meta name=\'viewport\' content=\'width=device-width initial-scale=1\'>");
document.writeln("");
document.writeln("<link href=\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap\' rel=\'stylesheet\' type=\'text/css\' /><style type=\'text/css\'>html {overflow-x: initial !important;}:root { --bg-color:#ffffff; --text-color:#333333; --select-text-bg-color:#B5D6FC; --select-text-font-color:auto; --monospace:\'Lucida Console\',Consolas,\'Courier\',monospace; --title-bar-height:20px; }");
document.writeln(".mac-os-11 { --title-bar-height:28px; }");
document.writeln("html { font-size: 14px; background-color: var(--bg-color); color: var(--text-color); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; }");
document.writeln("h1, h2, h3, h4, h5 { white-space: pre-wrap; }");
document.writeln("body { margin: 0px; padding: 0px; height: auto; inset: 0px; font-size: 1rem; line-height: 1.42857; overflow-x: hidden; background: inherit; tab-size: 4; }");
document.writeln("iframe { margin: auto; }");
document.writeln("a.url { word-break: break-all; }");
document.writeln("a:active, a:hover { outline: 0px; }");
document.writeln(".in-text-selection, ::selection { text-shadow: none; background: var(--select-text-bg-color); color: var(--select-text-font-color); }");
document.writeln("#write { margin: 0px auto; height: auto; width: inherit; word-break: normal; overflow-wrap: break-word; position: relative; white-space: normal; overflow-x: visible; padding-top: 36px; }");
document.writeln("#write.first-line-indent p { text-indent: 2em; }");
document.writeln("#write.first-line-indent li p, #write.first-line-indent p * { text-indent: 0px; }");
document.writeln("#write.first-line-indent li { margin-left: 2em; }");
document.writeln(".for-image #write { padding-left: 8px; padding-right: 8px; }");
document.writeln("body.typora-export { padding-left: 30px; padding-right: 30px; }");
document.writeln(".typora-export .footnote-line, .typora-export li, .typora-export p { white-space: pre-wrap; }");
document.writeln(".typora-export .task-list-item input { pointer-events: none; }");
document.writeln("@media screen and (max-width: 500px) {");
document.writeln("  body.typora-export { padding-left: 0px; padding-right: 0px; }");
document.writeln("  #write { padding-left: 20px; padding-right: 20px; }");
document.writeln("}");
document.writeln("#write li > figure:last-child { margin-bottom: 0.5rem; }");
document.writeln("#write ol, #write ul { position: relative; }");
document.writeln("img { max-width: 100%; vertical-align: middle; image-orientation: from-image; }");
document.writeln("button, input, select, textarea { color: inherit; font: inherit; }");
document.writeln("input[type=\'checkbox\'], input[type=\'radio\'] { line-height: normal; padding: 0px; }");
document.writeln("*, ::after, ::before { box-sizing: border-box; }");
document.writeln("#write h1, #write h2, #write h3, #write h4, #write h5, #write h6, #write p, #write pre { width: inherit; }");
document.writeln("#write h1, #write h2, #write h3, #write h4, #write h5, #write h6, #write p { position: relative; }");
document.writeln("p { line-height: inherit; }");
document.writeln("h1, h2, h3, h4, h5, h6 { break-after: avoid-page; break-inside: avoid; orphans: 4; }");
document.writeln("p { orphans: 4; }");
document.writeln("h1 { font-size: 2rem; }");
document.writeln("h2 { font-size: 1.8rem; }");
document.writeln("h3 { font-size: 1.6rem; }");
document.writeln("h4 { font-size: 1.4rem; }");
document.writeln("h5 { font-size: 1.2rem; }");
document.writeln("h6 { font-size: 1rem; }");
document.writeln(".md-math-block, .md-rawblock, h1, h2, h3, h4, h5, h6, p { margin-top: 1rem; margin-bottom: 1rem; }");
document.writeln(".hidden { display: none; }");
document.writeln(".md-blockmeta { color: rgb(204, 204, 204); font-weight: 700; font-style: italic; }");
document.writeln("a { cursor: pointer; }");
document.writeln("sup.md-footnote { padding: 2px 4px; background-color: rgba(238, 238, 238, 0.7); color: rgb(85, 85, 85); border-radius: 4px; cursor: pointer; }");
document.writeln("sup.md-footnote a, sup.md-footnote a:hover { color: inherit; text-transform: inherit; text-decoration: inherit; }");
document.writeln("#write input[type=\'checkbox\'] { cursor: pointer; width: inherit; height: inherit; }");
document.writeln("figure { overflow-x: auto; margin: 1.2em 0px; max-width: calc(100% + 16px); padding: 0px; }");
document.writeln("figure > table { margin: 0px; }");
document.writeln("thead, tr { break-inside: avoid; break-after: auto; }");
document.writeln("thead { display: table-header-group; }");
document.writeln("table { border-collapse: collapse; border-spacing: 0px; width: 100%; overflow: auto; break-inside: auto; text-align: left; }");
document.writeln("table.md-table td { min-width: 32px; }");
document.writeln(".CodeMirror-gutters { border-right: 0px; background-color: inherit; }");
document.writeln(".CodeMirror-linenumber { user-select: none; }");
document.writeln(".CodeMirror { text-align: left; }");
document.writeln(".CodeMirror-placeholder { opacity: 0.3; }");
document.writeln(".CodeMirror pre { padding: 0px 4px; }");
document.writeln(".CodeMirror-lines { padding: 0px; }");
document.writeln("div.hr:focus { cursor: none; }");
document.writeln("#write pre { white-space: pre-wrap; }");
document.writeln("#write.fences-no-line-wrapping pre { white-space: pre; }");
document.writeln("#write pre.ty-contain-cm { white-space: normal; }");
document.writeln(".CodeMirror-gutters { margin-right: 4px; }");
document.writeln(".md-fences { font-size: 0.9rem; display: block; break-inside: avoid; text-align: left; overflow: visible; white-space: pre; background: inherit; position: relative !important; }");
document.writeln(".md-fences-adv-panel { width: 100%; margin-top: 10px; text-align: center; padding-top: 0px; padding-bottom: 8px; overflow-x: auto; }");
document.writeln("#write .md-fences.mock-cm { white-space: pre-wrap; }");
document.writeln(".md-fences.md-fences-with-lineno { padding-left: 0px; }");
document.writeln("#write.fences-no-line-wrapping .md-fences.mock-cm { white-space: pre; overflow-x: auto; }");
document.writeln(".md-fences.mock-cm.md-fences-with-lineno { padding-left: 8px; }");
document.writeln(".CodeMirror-line, twitterwidget { break-inside: avoid; }");
document.writeln("svg { break-inside: avoid; }");
document.writeln(".footnotes { opacity: 0.8; font-size: 0.9rem; margin-top: 1em; margin-bottom: 1em; }");
document.writeln(".footnotes + .footnotes { margin-top: 0px; }");
document.writeln(".md-reset { margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: top; background: 0px 0px; text-decoration: none; text-shadow: none; float: none; position: static; width: auto; height: auto; white-space: nowrap; cursor: inherit; -webkit-tap-highlight-color: transparent; line-height: normal; font-weight: 400; text-align: left; box-sizing: content-box; direction: ltr; }");
document.writeln("li div { padding-top: 0px; }");
document.writeln("blockquote { margin: 1rem 0px; }");
document.writeln("li .mathjax-block, li p { margin: 0.5rem 0px; }");
document.writeln("li blockquote { margin: 1rem 0px; }");
document.writeln("li { margin: 0px; position: relative; }");
document.writeln("blockquote > :last-child { margin-bottom: 0px; }");
document.writeln("blockquote > :first-child, li > :first-child { margin-top: 0px; }");
document.writeln(".footnotes-area { color: rgb(136, 136, 136); margin-top: 0.714rem; padding-bottom: 0.143rem; white-space: normal; }");
document.writeln("#write .footnote-line { white-space: pre-wrap; }");
document.writeln("@media print {");
document.writeln("  body, html { border: 1px solid transparent; height: 99%; break-after: avoid; break-before: avoid; font-variant-ligatures: no-common-ligatures; }");
document.writeln("  #write { margin-top: 0px; border-color: transparent !important; padding-top: 0px !important; padding-bottom: 0px !important; }");
document.writeln("  .typora-export * { -webkit-print-color-adjust: exact; }");
document.writeln("  .typora-export #write { break-after: avoid; }");
document.writeln("  .typora-export #write::after { height: 0px; }");
document.writeln("  .is-mac table { break-inside: avoid; }");
document.writeln("  #write > p:nth-child(1) { margin-top: 0px; }");
document.writeln("  .typora-export-show-outline .typora-export-sidebar { display: none; }");
document.writeln("  figure { overflow-x: visible; }");
document.writeln("}");
document.writeln(".footnote-line { margin-top: 0.714em; font-size: 0.7em; }");
document.writeln("a img, img a { cursor: pointer; }");
document.writeln("pre.md-meta-block { font-size: 0.8rem; min-height: 0.8rem; white-space: pre-wrap; background: rgb(204, 204, 204); display: block; overflow-x: hidden; }");
document.writeln("p > .md-image:only-child:not(.md-img-error) img, p > img:only-child { display: block; margin: auto; }");
document.writeln("#write.first-line-indent p > .md-image:only-child:not(.md-img-error) img { left: -2em; position: relative; }");
document.writeln("p > .md-image:only-child { display: inline-block; width: 100%; }");
document.writeln("#write .MathJax_Display { margin: 0.8em 0px 0px; }");
document.writeln(".md-math-block { width: 100%; }");
document.writeln(".md-math-block:not(:empty)::after { display: none; }");
document.writeln(".MathJax_ref { fill: currentcolor; }");
document.writeln("[contenteditable=\'true\']:active, [contenteditable=\'true\']:focus, [contenteditable=\'false\']:active, [contenteditable=\'false\']:focus { outline: 0px; box-shadow: none; }");
document.writeln(".md-task-list-item { position: relative; list-style-type: none; }");
document.writeln(".task-list-item.md-task-list-item { padding-left: 0px; }");
document.writeln(".md-task-list-item > input { position: absolute; top: 0px; left: 0px; margin-left: -1.2em; margin-top: calc(1em - 10px); border: none; }");
document.writeln(".math { font-size: 1rem; }");
document.writeln(".md-toc { min-height: 3.58rem; position: relative; font-size: 0.9rem; border-radius: 10px; }");
document.writeln(".md-toc-content { position: relative; margin-left: 0px; }");
document.writeln(".md-toc-content::after, .md-toc::after { display: none; }");
document.writeln(".md-toc-item { display: block; color: rgb(65, 131, 196); }");
document.writeln(".md-toc-item a { text-decoration: none; }");
document.writeln(".md-toc-inner:hover { text-decoration: underline; }");
document.writeln(".md-toc-inner { display: inline-block; cursor: pointer; }");
document.writeln(".md-toc-h1 .md-toc-inner { margin-left: 0px; font-weight: 700; }");
document.writeln(".md-toc-h2 .md-toc-inner { margin-left: 2em; }");
document.writeln(".md-toc-h3 .md-toc-inner { margin-left: 4em; }");
document.writeln(".md-toc-h4 .md-toc-inner { margin-left: 6em; }");
document.writeln(".md-toc-h5 .md-toc-inner { margin-left: 8em; }");
document.writeln(".md-toc-h6 .md-toc-inner { margin-left: 10em; }");
document.writeln("@media screen and (max-width: 48em) {");
document.writeln("  .md-toc-h3 .md-toc-inner { margin-left: 3.5em; }");
document.writeln("  .md-toc-h4 .md-toc-inner { margin-left: 5em; }");
document.writeln("  .md-toc-h5 .md-toc-inner { margin-left: 6.5em; }");
document.writeln("  .md-toc-h6 .md-toc-inner { margin-left: 8em; }");
document.writeln("}");
document.writeln("a.md-toc-inner { font-size: inherit; font-style: inherit; font-weight: inherit; line-height: inherit; }");
document.writeln(".footnote-line a:not(.reversefootnote) { color: inherit; }");
document.writeln(".reversefootnote { font-family: ui-monospace, sans-serif; }");
document.writeln(".md-attr { display: none; }");
document.writeln(".md-fn-count::after { content: \'.\'; }");
document.writeln("code, pre, samp, tt { font-family: var(--monospace); }");
document.writeln("kbd { margin: 0px 0.1em; padding: 0.1em 0.6em; font-size: 0.8em; color: rgb(36, 39, 41); background: rgb(255, 255, 255); border: 1px solid rgb(173, 179, 185); border-radius: 3px; box-shadow: rgba(12, 13, 14, 0.2) 0px 1px 0px, rgb(255, 255, 255) 0px 0px 0px 2px inset; white-space: nowrap; vertical-align: middle; }");
document.writeln(".md-comment { color: rgb(162, 127, 3); opacity: 0.6; font-family: var(--monospace); }");
document.writeln("code { text-align: left; vertical-align: initial; }");
document.writeln("a.md-print-anchor { white-space: pre !important; border-width: initial !important; border-style: none !important; border-color: initial !important; display: inline-block !important; position: absolute !important; width: 1px !important; right: 0px !important; outline: 0px !important; background: 0px 0px !important; text-decoration: initial !important; text-shadow: initial !important; }");
document.writeln(".os-windows.monocolor-emoji .md-emoji { font-family: \'Segoe UI Symbol\', sans-serif; }");
document.writeln(".md-diagram-panel > svg { max-width: 100%; }");
document.writeln("[lang=\'flow\'] svg, [lang=\'mermaid\'] svg { max-width: 100%; height: auto; }");
document.writeln("[lang=\'mermaid\'] .node text { font-size: 1rem; }");
document.writeln("table tr th { border-bottom: 0px; }");
document.writeln("video { max-width: 100%; display: block; margin: 0px auto; }");
document.writeln("iframe { max-width: 100%; width: 100%; border: none; }");
document.writeln(".highlight td, .highlight tr { border: 0px; }");
document.writeln("mark { background: rgb(255, 255, 0); color: rgb(0, 0, 0); }");
document.writeln(".md-html-inline .md-plain, .md-html-inline strong, mark .md-inline-math, mark strong { color: inherit; }");
document.writeln(".md-expand mark .md-meta { opacity: 0.3 !important; }");
document.writeln("mark .md-meta { color: rgb(0, 0, 0); }");
document.writeln("@media print {");
document.writeln("  .typora-export h1, .typora-export h2, .typora-export h3, .typora-export h4, .typora-export h5, .typora-export h6 { break-inside: avoid; }");
document.writeln("}");
document.writeln(".md-diagram-panel .messageText { stroke: none !important; }");
document.writeln(".md-diagram-panel .start-state { fill: var(--node-fill); }");
document.writeln(".md-diagram-panel .edgeLabel rect { opacity: 1 !important; }");
document.writeln(".md-fences.md-fences-math { font-size: 1em; }");
document.writeln(".md-fences-advanced:not(.md-focus) { padding: 0px; white-space: nowrap; border: 0px; }");
document.writeln(".md-fences-advanced:not(.md-focus) { background: inherit; }");
document.writeln(".typora-export-show-outline .typora-export-content { max-width: 1440px; margin: auto; display: flex; flex-direction: row; }");
document.writeln(".typora-export-sidebar { width: 300px; font-size: 0.8rem; margin-top: 80px; margin-right: 18px; }");
document.writeln(".typora-export-show-outline #write { --webkit-flex:2; flex: 2 1 0%; }");
document.writeln(".typora-export-sidebar .outline-content { position: fixed; top: 0px; max-height: 100%; overflow: hidden auto; padding-bottom: 30px; padding-top: 60px; width: 300px; }");
document.writeln("@media screen and (max-width: 1024px) {");
document.writeln("  .typora-export-sidebar, .typora-export-sidebar .outline-content { width: 240px; }");
document.writeln("}");
document.writeln("@media screen and (max-width: 800px) {");
document.writeln("  .typora-export-sidebar { display: none; }");
document.writeln("}");
document.writeln(".outline-content li, .outline-content ul { margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; list-style: none; overflow-wrap: anywhere; }");
document.writeln(".outline-content ul { margin-top: 0px; margin-bottom: 0px; }");
document.writeln(".outline-content strong { font-weight: 400; }");
document.writeln(".outline-expander { width: 1rem; height: 1.42857rem; position: relative; display: table-cell; vertical-align: middle; cursor: pointer; padding-left: 4px; }");
document.writeln(".outline-expander::before { content: \'\'; position: relative; font-family: Ionicons; display: inline-block; font-size: 8px; vertical-align: middle; }");
document.writeln(".outline-item { padding-top: 3px; padding-bottom: 3px; cursor: pointer; }");
document.writeln(".outline-expander:hover::before { content: \'\'; }");
document.writeln(".outline-h1 > .outline-item { padding-left: 0px; }");
document.writeln(".outline-h2 > .outline-item { padding-left: 1em; }");
document.writeln(".outline-h3 > .outline-item { padding-left: 2em; }");
document.writeln(".outline-h4 > .outline-item { padding-left: 3em; }");
document.writeln(".outline-h5 > .outline-item { padding-left: 4em; }");
document.writeln(".outline-h6 > .outline-item { padding-left: 5em; }");
document.writeln(".outline-label { cursor: pointer; display: table-cell; vertical-align: middle; text-decoration: none; color: inherit; }");
document.writeln(".outline-label:hover { text-decoration: underline; }");
document.writeln(".outline-item:hover { border-color: rgb(245, 245, 245); background-color: var(--item-hover-bg-color); }");
document.writeln(".outline-item:hover { margin-left: -28px; margin-right: -28px; border-left: 28px solid transparent; border-right: 28px solid transparent; }");
document.writeln(".outline-item-single .outline-expander::before, .outline-item-single .outline-expander:hover::before { display: none; }");
document.writeln(".outline-item-open > .outline-item > .outline-expander::before { content: \'\'; }");
document.writeln(".outline-children { display: none; }");
document.writeln(".info-panel-tab-wrapper { display: none; }");
document.writeln(".outline-item-open > .outline-children { display: block; }");
document.writeln(".typora-export .outline-item { padding-top: 1px; padding-bottom: 1px; }");
document.writeln(".typora-export .outline-item:hover { margin-right: -8px; border-right: 8px solid transparent; }");
document.writeln(".typora-export .outline-expander::before { content: \'+\'; font-family: inherit; top: -1px; }");
document.writeln(".typora-export .outline-expander:hover::before, .typora-export .outline-item-open > .outline-item > .outline-expander::before { content: \'−\'; }");
document.writeln(".typora-export-collapse-outline .outline-children { display: none; }");
document.writeln(".typora-export-collapse-outline .outline-item-open > .outline-children, .typora-export-no-collapse-outline .outline-children { display: block; }");
document.writeln(".typora-export-no-collapse-outline .outline-expander::before { content: \'\' !important; }");
document.writeln(".typora-export-show-outline .outline-item-active > .outline-item .outline-label { font-weight: 700; }");
document.writeln(".md-inline-math-container mjx-container { zoom: 0.95; }");
document.writeln("mjx-container { break-inside: avoid; }");
document.writeln("");
document.writeln("");
document.writeln("/*快速自定义配置*/");
document.writeln(":root {");
document.writeln("    --monospace: \'Iosevka Curly\', \'JetBrains Mono\', \'Fira Code\', \'Cascadia Code\', Menlo, \'Ubuntu Mono\', Consolas, HYZhengYuan; /*代码字体*/");
document.writeln("    --text-font: var(--monospace); /*正文字体*/");
document.writeln("    --title-font: var(--monospace); /*标题字体*/");
document.writeln("    --latex-font: var(--monospace); /*LaTeX字体(不含英语)*/");
document.writeln("    --text-line-height: 1.6; /*正文行间距*/");
document.writeln("    --code-line-height: 1.6; /*代码块行间距*/");
document.writeln("    --p-spacing: 0.8rem; /*段间距*/");
document.writeln("    --file-tree-text-size: 1.1rem; /*文件树大小*/");
document.writeln("    --toc-text-size: 1rem; /*大纲大小*/");
document.writeln("    --text-size: 14px; /*字体大小 推荐配置: 应用设置-外观-字体大小*/");
document.writeln("}/*");
document.writeln(" * MIT License");
document.writeln(" *");
document.writeln(" * Copyright (c) 2023 劉強東 https://github.com/liangjingkanji");
document.writeln(" *");
document.writeln(" * Permission is hereby granted, free of charge, to any person obtaining a copy");
document.writeln(" * of this software and associated documentation files (the \'Software\'), to deal");
document.writeln(" * in the Software without restriction, including without limitation the rights");
document.writeln(" * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
document.writeln(" * copies of the Software, and to permit persons to whom the Software is");
document.writeln(" * furnished to do so, subject to the following conditions:");
document.writeln(" *");
document.writeln(" * The above copyright notice and this permission notice shall be included in all");
document.writeln(" * copies or substantial portions of the Software.");
document.writeln(" *");
document.writeln(" * THE SOFTWARE IS PROVIDED \'AS IS\', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
document.writeln(" * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
document.writeln(" * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
document.writeln(" * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
document.writeln(" * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
document.writeln(" * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE");
document.writeln(" * SOFTWARE.");
document.writeln(" */");
document.writeln("@import url();");
document.writeln("@include-when-export url(\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap\');");
document.writeln("");
document.writeln(":root {");
document.writeln("    --text-color: #acb7c4;");
document.writeln("    --bg-color: #2b2b2b;");
document.writeln("    --control-text-color: var(--text-color);");
document.writeln("    --meta-content-color: var(--text-color);");
document.writeln("    --active-file-border-color: var(--drake-accent);");
document.writeln("    --rawblock-edit-panel-bd: var(--code-block-bg-color);");
document.writeln("    --item-hover-bg-color: #222222;");
document.writeln("    --active-file-bg-color: var(--item-hover-bg-color);");
document.writeln("    --mermaid-theme: night;");
document.writeln("");
document.writeln("    --blur-text-color: rgba(172, 183, 196, 0.5);");
document.writeln("    --md-char-color: #535455;");
document.writeln("    --side-bar-bg-color: var(--bg-color);");
document.writeln("    --search-select-bg-color: #ffffff;");
document.writeln("    --search-select-text-color: var(--bg-color);");
document.writeln("    --select-text-bg-color: #3473B068;");
document.writeln("    --window-border: 1px solid #282828;");
document.writeln("");
document.writeln("    --drake-accent: #3473b0;");
document.writeln("    --drake-highlight: #58a1d6;");
document.writeln("    --a-color: var(--drake-highlight);");
document.writeln("    --variable-color: var(--drake-highlight);");
document.writeln("    --outline-active-color: var(--a-color);");
document.writeln("    --code-block-bg-color: var(--item-hover-bg-color);");
document.writeln("    --code-block-color: #A9B7C6;");
document.writeln("    --title-color: #bbc9d7;");
document.writeln("    --blockquote-border-color: var(--drake-accent);");
document.writeln("    --blockquote-color: var(--text-color);");
document.writeln("    --blockquote-bg-color: rgba(52, 115, 176, 0.1);");
document.writeln("    --strong-color: var(--title-color);");
document.writeln("    --h2-underline-color: var(--title-color);");
document.writeln("    --horizontal-divider-color: var(--title-color);");
document.writeln("    --height-light-color: var(--drake-highlight);");
document.writeln("    --height-light-border-color: var(--drake-highlight);");
document.writeln("    --yaml-color: #787878;");
document.writeln("    --yaml-bg-color: var(--code-block-bg-color);");
document.writeln("    --footnotes-bg-color: var(--item-hover-bg-color);");
document.writeln("    --footnotes-highlight: #FFD760;");
document.writeln("    --table-border-color: #383838;");
document.writeln("    --table-header-bg-color: var(--item-hover-bg-color);");
document.writeln("    --table-bg-color: var(--bg-color);");
document.writeln("    --table-n2-bg-color: var(--table-header-bg-color);");
document.writeln("    --input-bg-color: var(--item-hover-bg-color);");
document.writeln("    --btn-hover-bg-color: var(--item-hover-bg-color);");
document.writeln("    --checkbox-checked: url(\'data:image/svg+xml,%3Csvg class=\'icon\' viewBox=\'0 0 1024 1024\' xmlns=\'http://www.w3.org/2000/svg\' width=\'200\' height=\'200\'%3E%3Cpath d=\'M425.984 726.016l384-384-59.99-61.995-324.01 324.011-152.021-152.021L213.973 512zm384-598.016q36.01 0 61.013 25.984T896 213.974v596.01q0 34.005-25.003 59.99t-61.013 25.983h-596.01q-36.011 0-61.014-25.984t-25.003-59.989v-596.01q0-34.006 25.003-59.99T213.973 128h596.011z\' fill=\'%2365b73b\'/%3E%3C/svg%3E\');");
document.writeln("    --checkbox-unchecked: url(\'data:image/svg+xml,%3Csvg class=\'icon\' viewBox=\'0 0 1024 1024\' xmlns=\'http://www.w3.org/2000/svg\' width=\'200\' height=\'200\'%3E%3Cpath d=\'M810.667 213.333v597.334H213.333V213.333h597.334m0-85.333H213.333C166.4 128 128 166.4 128 213.333v597.334C128 857.6 166.4 896 213.333 896h597.334C857.6 896 896 857.6 896 810.667V213.333C896 166.4 857.6 128 810.667 128z\' fill=\'%23acb7c4\'/%3E%3C/svg%3E\');");
document.writeln("}");
document.writeln("");
document.writeln("html {");
document.writeln("    font-size: var(--text-size);");
document.writeln("}");
document.writeln("");
document.writeln("body {");
document.writeln("    font-family: var(--text-font) !important;");
document.writeln("    color: var(--text-color);");
document.writeln("    -webkit-font-feature-settings: \'liga\' on, \'calt\' on;");
document.writeln("    -webkit-font-smoothing: subpixel-antialiased;");
document.writeln("    text-rendering: optimizeLegibility;");
document.writeln("    letter-spacing: 0;");
document.writeln("    margin: 0;");
document.writeln("    overflow-x: hidden;");
document.writeln("}");
document.writeln("");
document.writeln("p {");
document.writeln("    line-height: var(--text-line-height);");
document.writeln("}");
document.writeln("");
document.writeln("/*code block*/");
document.writeln(".md-fences {");
document.writeln("    font-size: 1rem;");
document.writeln("    padding: 0.5rem !important;");
document.writeln("    border-radius: 2px;");
document.writeln("    word-wrap: normal;");
document.writeln("    background-color: var(--code-block-bg-color);");
document.writeln("    color: var(--code-block-color);");
document.writeln("    border: none;");
document.writeln("    line-height: var(--code-line-height);");
document.writeln("}");
document.writeln("");
document.writeln("/*inline latex*/");
document.writeln(".MathJax {");
document.writeln("    font-size: 120% !important;");
document.writeln("}");
document.writeln(".MathJax text, .MathJax use {");
document.writeln("    font-family: var(--latex-font);");
document.writeln("}");
document.writeln("/*math-block latex*/");
document.writeln(".md-math-block .MathJax {");
document.writeln("    font-size: 130% !important;");
document.writeln("}");
document.writeln("");
document.writeln("/*mermaid*/");
document.writeln("[id^=mermaidChart] .cluster rect {");
document.writeln("    fill: var(--table-n2-bg-color) !important;");
document.writeln("    stroke: var(--table-border-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] .grid .tick text,");
document.writeln("[id^=mermaidChart] .titleText {");
document.writeln("    fill: var(--text-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] .clusters span.nodeLabel {");
document.writeln("    color: var(--text-color) !important;");
document.writeln("    line-height: 1.8rem;");
document.writeln("}");
document.writeln("[mermaid-type=\'journey\'] line {");
document.writeln("    stroke: #7a7a7a !important;");
document.writeln("}");
document.writeln("[mermaid-type=\'journey\'] .label {");
document.writeln("    color: #333 !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] .relationshipLabelBox {");
document.writeln("    fill: var(--bg-color) !important;");
document.writeln("    opacity: 1 !important;");
document.writeln("    background-color: var(--bg-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] .legend {");
document.writeln("    fill: var(--text-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] g.label {");
document.writeln("    font-size: 1rem !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] line.divider {");
document.writeln("    stroke: var(--table-border-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] span.nodeLabel {");
document.writeln("    color: var(--code-block-color) !important;");
document.writeln("    line-height: 1.8rem;");
document.writeln("}");
document.writeln("tspan {");
document.writeln("    color: var(--text-color)");
document.writeln("}");
document.writeln("[id^=mermaidChart] .entityLabel {");
document.writeln("    fill: var(--code-block-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] {");
document.writeln("    fill: var(--text-color) !important;");
document.writeln("}");
document.writeln("[id^=mermaidChart] rect.rect {");
document.writeln("    fill: rgba(175, 255, 212, 0.3) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview text.actor > tspan { /*方块文字*/");
document.writeln("    fill: var(--code-block-color) !important;");
document.writeln("    stroke: none !important;");
document.writeln("    font-family: var(--text-font) !important;");
document.writeln("    font-size: 1rem !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .actor, .md-diagram-panel-preview .entityBox { /*方块*/");
document.writeln("    stroke: var(--table-border-color) !important;");
document.writeln("    fill: var(--code-block-bg-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .actor-line { /*竖线*/");
document.writeln("    stroke: var(--text-color) !important;");
document.writeln("    stroke-width: 1px;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .messageLine0 { /*横线*/");
document.writeln("    stroke-width: 1.5;");
document.writeln("    stroke-dasharray: none;");
document.writeln("    stroke: var(--text-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .messageLine1 { /*虚线*/");
document.writeln("    stroke-width: 1.5 !important;");
document.writeln("    stroke-dasharray: 2, 2 !important;");
document.writeln("    stroke: var(--text-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .messageText { /*描述文字*/");
document.writeln("    fill: var(--text-color) !important;");
document.writeln("    font-family: var(--text-font) !important;");
document.writeln("    font-size: 1rem !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .activation0 { /*长方形*/");
document.writeln("    fill: #e6e6e6 !important;");
document.writeln("    stroke: var(--text-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .labelText, .md-diagram-panel-preview .labelText > tspan { /*循环标记*/");
document.writeln("    fill: var(--code-block-color) !important;");
document.writeln("    font-family: var(--text-font) !important;");
document.writeln("    font-size: 1rem !important;");
document.writeln("    dominant-baseline: unset;");
document.writeln("    alignment-baseline: unset;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .labelBox { /*循环标记背景*/");
document.writeln("    stroke: var(--table-border-color) !important;");
document.writeln("    fill: var(--code-block-bg-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .loopLine { /*循环标记虚线*/");
document.writeln("    stroke: var(--text-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .loopText, .md-diagram-panel-preview .loopText > tspan { /*循环名称*/");
document.writeln("    fill: var(--text-color) !important;");
document.writeln("    font-size: 1rem !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .sequenceNumber { /*序号*/");
document.writeln("    fill: var(--bg-color) !important;");
document.writeln("}");
document.writeln("pre.md-fences-advanced.md-focus .md-fences-adv-panel {");
document.writeln("    border: none;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .edgePath .path { /*箭头*/");
document.writeln("    stroke: var(--text-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .edgeLabel rect { /*条件文字背景*/");
document.writeln("    fill: var(--bg-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .edgeLabel span { /*条件文字*/");
document.writeln("    color: var(--text-color) !important;");
document.writeln("    background: var(--bg-color) !important;");
document.writeln("}");
document.writeln(".md-diagram-panel-preview .node rect,");
document.writeln(".md-diagram-panel-preview .node circle,");
document.writeln(".md-diagram-panel-preview .node ellipse,");
document.writeln(".md-diagram-panel-preview .node polygon,");
document.writeln(".md-diagram-panel-preview .node path { /*形状*/");
document.writeln("    stroke: var(--table-border-color) !important;");
document.writeln("    fill: var(--code-block-bg-color) !important;");
document.writeln("}");
document.writeln("#write .md-diagram-panel .md-diagram-panel-preview div { /*形状内文字*/");
document.writeln("    color: var(--code-block-color);");
document.writeln("    font-family: var(--text-font) !important;");
document.writeln("    font-size: 1rem !important;");
document.writeln("}");
document.writeln("");
document.writeln("/*code snippet*/");
document.writeln("#write code, tt {");
document.writeln("    margin: 0 2px;");
document.writeln("    color: var(--drake-highlight);");
document.writeln("}");
document.writeln("");
document.writeln("/*variable*/");
document.writeln("var {");
document.writeln("    color: var(--variable-color);");
document.writeln("    font-weight: bold;");
document.writeln("}");
document.writeln("");
document.writeln("/*raw block*/");
document.writeln(".md-rawblock-control:not(.md-rawblock-tooltip) {");
document.writeln("    border-radius: 2px 0 2px 2px;");
document.writeln("    padding: 0.2rem !important;");
document.writeln("}");
document.writeln(".md-rawblock:hover > .md-rawblock-container {");
document.writeln("    background: none;");
document.writeln("}");
document.writeln(".md-rawblock-input {");
document.writeln("    font-size: 1rem;");
document.writeln("}");
document.writeln(".md-rawblock-tooltip-btn:hover {");
document.writeln("    background: none;");
document.writeln("}");
document.writeln(".md-rawblock:hover > .md-rawblock-tooltip {");
document.writeln("    border-radius: 2px 2px 0 0;");
document.writeln("    margin-bottom: 2px !important;");
document.writeln("}");
document.writeln(".md-rawblock-tooltip.md-rawblock-control {");
document.writeln("    border-radius: 2px 2px 0 0;");
document.writeln("    color: var(--code-block-color);");
document.writeln("}");
document.writeln(".md-rawblock-tooltip-name {");
document.writeln("    color: var(--code-block-color);");
document.writeln("    opacity: 1;");
document.writeln("}");
document.writeln("");
document.writeln("/*quote block*/");
document.writeln("blockquote:before {");
document.writeln("    display: block;");
document.writeln("    position: absolute;");
document.writeln("    content: \'\';");
document.writeln("    width: 4px;");
document.writeln("    left: 0;");
document.writeln("    top: 0;");
document.writeln("    height: 100%;");
document.writeln("    background-color: var(--blockquote-border-color);");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln("blockquote {");
document.writeln("    color: var(--blockquote-color);");
document.writeln("    border-radius: 2px;");
document.writeln("    padding: 10px 16px;");
document.writeln("    background-color: var(--blockquote-bg-color);");
document.writeln("    position: relative;");
document.writeln("    border-left: none;");
document.writeln("}");
document.writeln("");
document.writeln("strong {");
document.writeln("    color: var(--strong-color);");
document.writeln("    font-weight: bold;");
document.writeln("}");
document.writeln("#write blockquote strong {");
document.writeln("    color: var(--blockquote-color);");
document.writeln("}");
document.writeln("");
document.writeln("/*link*/");
document.writeln("#write a {");
document.writeln("    color: var(--a-color);");
document.writeln("    text-decoration: none;");
document.writeln("}");
document.writeln("#write h2 a .md-plain {");
document.writeln("    border-bottom: .2rem solid var(--a-color);");
document.writeln("}");
document.writeln(".on-focus-mode #write a .md-plain, .on-focus-mode .md-htmlblock-container a:hover {");
document.writeln("    border-bottom: .1rem solid var(--blur-text-color);");
document.writeln("}");
document.writeln("#write a .md-plain, .md-htmlblock-container a:hover,");
document.writeln(".on-focus-mode #write .md-focus a .md-plain, .md-focus .md-htmlblock-container a:hover {");
document.writeln("    border-bottom: .1rem solid var(--a-color);");
document.writeln("}");
document.writeln("[md-inline=link] a {");
document.writeln("    margin: 0 .2rem;");
document.writeln("}");
document.writeln("a:any-link {");
document.writeln("    color: var(--a-color);");
document.writeln("}");
document.writeln("");
document.writeln("img {");
document.writeln("    border-left: none;");
document.writeln("    border-right: none;");
document.writeln("    vertical-align: baseline;");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln("#write {");
document.writeln("    max-width: 1200px;");
document.writeln("    margin: 0 auto;");
document.writeln("    padding: 20px 30px 100px;");
document.writeln("}");
document.writeln("#typora-source .CodeMirror-lines {");
document.writeln("    max-width: 1200px;");
document.writeln("}");
document.writeln("");
document.writeln("#write > ul:first-child,");
document.writeln("#write > ol:first-child {");
document.writeln("    margin-top: 30px;");
document.writeln("}");
document.writeln("");
document.writeln("body > *:first-child {");
document.writeln("    margin-top: 0 !important;");
document.writeln("}");
document.writeln("");
document.writeln("body > *:last-child {");
document.writeln("    margin-bottom: 0 !important;");
document.writeln("}");
document.writeln("");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6 {");
document.writeln("    font-family: var(--title-font);");
document.writeln("    position: relative;");
document.writeln("    margin-top: 2rem;");
document.writeln("    margin-bottom: 1rem;");
document.writeln("    font-weight: bold;");
document.writeln("    line-height: 1.4;");
document.writeln("    cursor: text;");
document.writeln("    color: var(--title-color);");
document.writeln("}");
document.writeln("");
document.writeln("h3.md-focus:before, h4.md-focus:before, h5.md-focus:before, h6.md-focus:before {");
document.writeln("    visibility: hidden;");
document.writeln("}");
document.writeln("");
document.writeln("h1 {");
document.writeln("    font-size: 2rem;");
document.writeln("    text-align: center;");
document.writeln("    margin-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("h2 {");
document.writeln("    font-size: 1.8rem;");
document.writeln("    margin-bottom: 1.5rem;");
document.writeln("}");
document.writeln("");
document.writeln(".on-focus-mode h2.md-end-block.md-heading:not(.md-focus):not(.md-focus-container):after {");
document.writeln("    background-color: var(--blur-text-color) !important;");
document.writeln("}");
document.writeln("");
document.writeln("h3 {");
document.writeln("    font-size: 1.4rem;");
document.writeln("}");
document.writeln("");
document.writeln("h4 {");
document.writeln("    font-size: 1.2rem;");
document.writeln("}");
document.writeln("");
document.writeln("h5 {");
document.writeln("    font-size: 1rem;");
document.writeln("}");
document.writeln("");
document.writeln("h6 {");
document.writeln("    font-size: 1rem;");
document.writeln("}");
document.writeln("");
document.writeln("h1:hover a.anchor,");
document.writeln("h2:hover a.anchor,");
document.writeln("h3:hover a.anchor,");
document.writeln("h4:hover a.anchor,");
document.writeln("h5:hover a.anchor,");
document.writeln("h6:hover a.anchor {");
document.writeln("    text-decoration: none;");
document.writeln("}");
document.writeln("");
document.writeln("h1 tt,");
document.writeln("h1 code {");
document.writeln("    font-size: inherit !important;");
document.writeln("}");
document.writeln("");
document.writeln("h2 tt,");
document.writeln("h2 code {");
document.writeln("    font-size: inherit !important;");
document.writeln("}");
document.writeln("");
document.writeln("h3 tt,");
document.writeln("h3 code {");
document.writeln("    font-size: inherit !important;");
document.writeln("}");
document.writeln("");
document.writeln("h4 tt,");
document.writeln("h4 code {");
document.writeln("    font-size: inherit !important;");
document.writeln("}");
document.writeln("");
document.writeln("h5 tt,");
document.writeln("h5 code {");
document.writeln("    font-size: inherit !important;");
document.writeln("}");
document.writeln("");
document.writeln("h6 tt,");
document.writeln("h6 code {");
document.writeln("    font-size: inherit !important;");
document.writeln("}");
document.writeln("");
document.writeln("p, blockquote, ul, ol, dl, table {");
document.writeln("    margin: var(--p-spacing) 0;");
document.writeln("}");
document.writeln("");
document.writeln("li > ol,");
document.writeln("li > ul {");
document.writeln("    margin: 0 0;");
document.writeln("}");
document.writeln("li {");
document.writeln("    margin: 0.5em 0;");
document.writeln("}");
document.writeln("");
document.writeln("hr {");
document.writeln("    height: 2px;");
document.writeln("    padding: 0;");
document.writeln("    margin: 16px 0;");
document.writeln("    background-color: var(--horizontal-divider-color);");
document.writeln("    border: 0 none;");
document.writeln("    overflow: hidden;");
document.writeln("    box-sizing: content-box;");
document.writeln("}");
document.writeln("");
document.writeln("body > h2:first-child {");
document.writeln("    margin-top: 0;");
document.writeln("    padding-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("body > h1:first-child {");
document.writeln("    margin-top: 0;");
document.writeln("    padding-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("body > h1:first-child + h2 {");
document.writeln("    margin-top: 0;");
document.writeln("    padding-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("body > h3:first-child,");
document.writeln("body > h4:first-child,");
document.writeln("body > h5:first-child,");
document.writeln("body > h6:first-child {");
document.writeln("    margin-top: 0;");
document.writeln("    padding-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("a:first-child h1,");
document.writeln("a:first-child h2,");
document.writeln("a:first-child h3,");
document.writeln("a:first-child h4,");
document.writeln("a:first-child h5,");
document.writeln("a:first-child h6 {");
document.writeln("    margin-top: 0;");
document.writeln("    padding-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("h1 p,");
document.writeln("h2 p,");
document.writeln("h3 p,");
document.writeln("h4 p,");
document.writeln("h5 p,");
document.writeln("h6 p {");
document.writeln("    margin-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("li p.first {");
document.writeln("    display: inline-block;");
document.writeln("}");
document.writeln("");
document.writeln("ul, ol {");
document.writeln("    padding-inline-start: 2em;");
document.writeln("}");
document.writeln("");
document.writeln("ul:first-child,");
document.writeln("ol:first-child {");
document.writeln("    margin-top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("ul:last-child,");
document.writeln("ol:last-child {");
document.writeln("    margin-bottom: 0;");
document.writeln("}");
document.writeln("");
document.writeln(".ty-table-edit {");
document.writeln("    margin-top: -1rem !important;");
document.writeln("}");
document.writeln("#write table {");
document.writeln("    margin-top: 1rem;");
document.writeln("    word-break: initial;");
document.writeln("    background-color: var(--table-bg-color);");
document.writeln("}");
document.writeln("table tr {");
document.writeln("    border-top: .1em solid var(--table-border-color);");
document.writeln("    margin: 0;");
document.writeln("    padding: 0;");
document.writeln("}");
document.writeln("table th {");
document.writeln("    font-weight: bold;");
document.writeln("    border: .1em solid var(--table-border-color);");
document.writeln("    border-bottom: 0;");
document.writeln("    margin: 0;");
document.writeln("    padding: 6px 13px;");
document.writeln("}");
document.writeln("table td {");
document.writeln("    border: .1em solid var(--table-border-color);");
document.writeln("    margin: 0;");
document.writeln("    padding: 6px 13px;");
document.writeln("}");
document.writeln("table thead {");
document.writeln("    background-color: var(--table-header-bg-color);");
document.writeln("}");
document.writeln("table tr:nth-child(2n) {");
document.writeln("    background-color: var(--table-n2-bg-color);");
document.writeln("}");
document.writeln("table tr th:first-child,");
document.writeln("table tr td:first-child {");
document.writeln("    margin-top: 0;");
document.writeln("}");
document.writeln("table tr th:last-child,");
document.writeln("table tr td:last-child {");
document.writeln("    margin-bottom: 0;");
document.writeln("}");
document.writeln("");
document.writeln("#write em {");
document.writeln("    padding: 0 5px 0 2px;");
document.writeln("}");
document.writeln("");
document.writeln("#write table thead th {");
document.writeln("    background-color: var(--table-header-bg-color);");
document.writeln("}");
document.writeln("");
document.writeln("/* height light */");
document.writeln("#write mark {");
document.writeln("    border: .1em solid var(--height-light-border-color);");
document.writeln("    color: var(--height-light-color);");
document.writeln("    background-color: transparent;");
document.writeln("    padding: .1rem .5rem;");
document.writeln("    border-radius: 2rem;");
document.writeln("    margin: 0 .2rem;");
document.writeln("    font-size: .95rem;");
document.writeln("}");
document.writeln("");
document.writeln("/*shortcut*/");
document.writeln("kbd {");
document.writeln("    border: .1em solid #5b5b5e;");
document.writeln("    background: transparent;");
document.writeln("    color: var(--text-color);");
document.writeln("    margin: 0 .4rem;");
document.writeln("    font-family: var(--text-font) !important;");
document.writeln("    font-size: .95rem;");
document.writeln("    padding: .3em .4em;");
document.writeln("    border-radius: .4em;");
document.writeln("    box-shadow: .1em .1em .2em rgba(0, 0, 0, 0.3);");
document.writeln("}");
document.writeln("");
document.writeln("#write del {");
document.writeln("    padding: 1px 2px;");
document.writeln("}");
document.writeln("");
document.writeln(".md-task-list-item > input {");
document.writeln("    margin-left: -1.3em;");
document.writeln("}");
document.writeln("");
document.writeln("@media print {");
document.writeln("    html {");
document.writeln("        font-size: 12px;");
document.writeln("    }");
document.writeln("");
document.writeln("    table,");
document.writeln("    pre {");
document.writeln("        page-break-inside: avoid;");
document.writeln("    }");
document.writeln("");
document.writeln("    pre {");
document.writeln("        word-wrap: break-word;");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln("/*YAML*/");
document.writeln("#write pre.md-meta-block {");
document.writeln("    padding: 1rem;");
document.writeln("    font-size: 1rem;");
document.writeln("    line-height: 1.45;");
document.writeln("    background-color: var(--yaml-bg-color);");
document.writeln("    border: 0;");
document.writeln("    border-radius: 2px;");
document.writeln("    color: var(--yaml-color);");
document.writeln("    margin-top: 0 !important;");
document.writeln("}");
document.writeln("");
document.writeln(".mathjax-block > .code-tooltip {");
document.writeln("    bottom: .375rem;");
document.writeln("}");
document.writeln("");
document.writeln("#write > h3.md-focus:before {");
document.writeln("    left: -1.5625rem;");
document.writeln("    top: .375rem;");
document.writeln("}");
document.writeln("");
document.writeln("#write > h4.md-focus:before {");
document.writeln("    left: -1.5625rem;");
document.writeln("    top: .285714286rem;");
document.writeln("}");
document.writeln("");
document.writeln("#write > h5.md-focus:before {");
document.writeln("    left: -1.5625rem;");
document.writeln("    top: .285714286rem;");
document.writeln("}");
document.writeln("");
document.writeln("#write > h6.md-focus:before {");
document.writeln("    left: -1.5625rem;");
document.writeln("    top: .285714286rem;");
document.writeln("}");
document.writeln("");
document.writeln(".md-image > .md-meta {");
document.writeln("    border-radius: 2px;");
document.writeln("    font-family: initial;");
document.writeln("    padding: 2px 0 0 4px;");
document.writeln("    color: inherit;");
document.writeln("}");
document.writeln("");
document.writeln(".md-tag {");
document.writeln("    color: inherit;");
document.writeln("}");
document.writeln("");
document.writeln(".md-toc {");
document.writeln("    margin-top: 20px;");
document.writeln("    padding-bottom: 20px;");
document.writeln("}");
document.writeln("");
document.writeln(".typora-quick-open-item {");
document.writeln("    font-size: 1rem !important;");
document.writeln("    height: 50px;");
document.writeln("    padding-left: 8px;");
document.writeln("    padding-top: 4px;");
document.writeln("    padding-bottom: 4px;");
document.writeln("}");
document.writeln("");
document.writeln("#typora-quick-open {");
document.writeln("    box-shadow: 0 0 8px #00000045;");
document.writeln("    padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln(".ty-quick-open-category.ty-has-prev .ty-quick-open-category-title {");
document.writeln("    border-top: none;");
document.writeln("}");
document.writeln("");
document.writeln("#typora-quick-open-input {");
document.writeln("    margin: 8px;");
document.writeln("    box-shadow: none;");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln("#typora-quick-open-input input {");
document.writeln("    font-size: 1rem;");
document.writeln("    box-shadow: none;");
document.writeln("    padding-top: 2px;");
document.writeln("    padding-left: 10px;");
document.writeln("    padding-right: 10px;");
document.writeln("    line-height: 32px;");
document.writeln("    max-height: 32px;");
document.writeln("    border: none;");
document.writeln("}");
document.writeln("");
document.writeln(".modal-dialog#typora-quick-open {");
document.writeln("    border-radius: 8px;");
document.writeln("}");
document.writeln("");
document.writeln(".ty-quick-open-category-title {");
document.writeln("    padding-left: 8px;");
document.writeln("    color: #BEBEBE;");
document.writeln("    font-size: 0.8rem;");
document.writeln("    margin-bottom: 4px;");
document.writeln("}");
document.writeln("");
document.writeln(".typora-quick-open-item-path {");
document.writeln("    font-size: 0.8rem;");
document.writeln("    text-overflow: ellipsis;");
document.writeln("    white-space: nowrap;");
document.writeln("    margin-top: 1px;");
document.writeln("}");
document.writeln("");
document.writeln("/*search input*/");
document.writeln(".form-control {");
document.writeln("    border: none;");
document.writeln("    border-radius: 2px;");
document.writeln("    box-shadow: none;");
document.writeln("}");
document.writeln("");
document.writeln("#md-searchpanel .btn {");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln("#search-panel-replaceall-btn {");
document.writeln("    padding-right: 5px !important;");
document.writeln("    text-align: center !important;");
document.writeln("}");
document.writeln("");
document.writeln("#search-panel-replace-btn {");
document.writeln("    text-align: center !important;");
document.writeln("}");
document.writeln("");
document.writeln("#md-searchpanel input {");
document.writeln("    background: var(--input-bg-color);");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln(".searchpanel-search-option-btn {");
document.writeln("    border-radius: 2px;");
document.writeln("    border: none;");
document.writeln("    background: transparent;");
document.writeln("    color: var(--text-color);");
document.writeln("}");
document.writeln("");
document.writeln(".searchpanel-search-option-btn.active {");
document.writeln("    background: var(--text-color);");
document.writeln("    color: var(--bg-color);");
document.writeln("}");
document.writeln("");
document.writeln(".form-control:focus {");
document.writeln("    box-shadow: none;");
document.writeln("}");
document.writeln("");
document.writeln("#md-notification:before {");
document.writeln("    top: 10px;");
document.writeln("}");
document.writeln("");
document.writeln("/** focus mode */");
document.writeln(".on-focus-mode blockquote {");
document.writeln("    border-left-color: rgba(85, 85, 85, 0.12);");
document.writeln("}");
document.writeln("");
document.writeln("header,");
document.writeln(".context-menu,");
document.writeln(".megamenu-content,");
document.writeln("footer {");
document.writeln("    font-family: initial;");
document.writeln("}");
document.writeln("");
document.writeln("/*sidebar*/");
document.writeln(".file-library-node.file-tree-node.file-node-root {");
document.writeln("    font-size: var(--file-tree-text-size);");
document.writeln("}");
document.writeln(".file-node-content:hover .file-node-icon,");
document.writeln(".file-node-content:hover .file-node-open-state {");
document.writeln("    visibility: visible;");
document.writeln("}");
document.writeln(".file-node-content {");
document.writeln("    display: flex;");
document.writeln("    align-items: center;");
document.writeln("}");
document.writeln(".file-node-open-state {");
document.writeln("    margin-right: .5rem;");
document.writeln("}");
document.writeln(".file-node-icon {");
document.writeln("    margin-right: .5rem;");
document.writeln("}");
document.writeln("");
document.writeln("#typora-sidebar {");
document.writeln("    font-size: inherit;");
document.writeln("    font-family: var(--title-font);");
document.writeln("}");
document.writeln("");
document.writeln(".sidebar-tabs {");
document.writeln("    border-bottom: none;");
document.writeln("}");
document.writeln("");
document.writeln(".file-list-item-summary, .file-list-item-parent-loc, .file-list-item-time, .file-list-item-summary {");
document.writeln("    font-size: 0.9rem !important;");
document.writeln("    font-family: var(--text-font);");
document.writeln("}");
document.writeln("");
document.writeln(".file-list-item-file-ext-part {");
document.writeln("    display: none;");
document.writeln("}");
document.writeln("");
document.writeln(".outline-item {");
document.writeln("    font-size: var(--toc-text-size);");
document.writeln("}");
document.writeln("");
document.writeln("/*footnotes mark*/");
document.writeln("#write .md-footnote {");
document.writeln("    background-color: inherit;");
document.writeln("    color: var(--drake-highlight);");
document.writeln("    font-size: 0.9rem;");
document.writeln("    border-radius: 0.9rem;");
document.writeln("    padding-left: 0;");
document.writeln("}");
document.writeln("");
document.writeln("#write .md-footnote:before {");
document.writeln("    content: \'[\';");
document.writeln("}");
document.writeln("");
document.writeln("#write .md-footnote:after {");
document.writeln("    content: \']\';");
document.writeln("}");
document.writeln("");
document.writeln("/*footnotes content*/");
document.writeln(".md-hover-tip .code-tooltip-content {");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln("/*footnotes title*/");
document.writeln("span.md-def-name {");
document.writeln("    padding-right: 3ch;");
document.writeln("    padding-left: 0;");
document.writeln("    position: relative;");
document.writeln("    font-weight: normal;");
document.writeln("}");
document.writeln("");
document.writeln("/*footnotes desc*/");
document.writeln(".footnotes {");
document.writeln("    font-size: 1rem;");
document.writeln("    font-weight: normal;");
document.writeln("    color: var(--text-color);");
document.writeln("    position: relative;");
document.writeln("}");
document.writeln("");
document.writeln("/*footnotes tooltip text*/");
document.writeln(".code-tooltip-content .md-plain {");
document.writeln("    font-size: 0.9rem;");
document.writeln("    font-family: inherit;");
document.writeln("}");
document.writeln("");
document.writeln(".code-tooltip-content code {");
document.writeln("    padding: 0 2px;");
document.writeln("    font-family: inherit;");
document.writeln("    color: var(--footnotes-highlight);");
document.writeln("    background-color: inherit;");
document.writeln("}");
document.writeln("");
document.writeln(".code-tooltip-content a {");
document.writeln("    color: var(--footnotes-highlight);");
document.writeln("}");
document.writeln("");
document.writeln("div.code-tooltip-content {");
document.writeln("    box-shadow: 0 0 8px #00000045;");
document.writeln("    background: var(--footnotes-bg-color);");
document.writeln("}");
document.writeln("");
document.writeln(".footnotes {");
document.writeln("    opacity: 1;");
document.writeln("}");
document.writeln("");
document.writeln(".md-def-name:after {");
document.writeln("    content: \'. ^\';");
document.writeln("    color: var(--text-color);");
document.writeln("}");
document.writeln("");
document.writeln(".md-def-footnote .md-def-name:before {");
document.writeln("    content: \'\';");
document.writeln("    color: var(--text-color);");
document.writeln("    position: absolute;");
document.writeln("}");
document.writeln("");
document.writeln(".md-def-name:before {");
document.writeln("    content: \'\';");
document.writeln("    color: var(--text-color);");
document.writeln("    position: absolute;");
document.writeln("}");
document.writeln("");
document.writeln(".md-content.md-url, .md-def-content.md-def-url.md-auto-disp {");
document.writeln("    text-decoration: none;");
document.writeln("    border-bottom: .1rem solid var(--text-color);");
document.writeln("}");
document.writeln("");
document.writeln(".CodeMirror-scroll::-webkit-scrollbar {");
document.writeln("    display: none;");
document.writeln("}");
document.writeln("");
document.writeln(".file-list-item-summary {");
document.writeln("    font-size: 1em;");
document.writeln("}");
document.writeln("");
document.writeln(".pin-outline #outline-content .outline-active strong, .pin-outline .outline-active {");
document.writeln("    font-weight: 500;");
document.writeln("    color: var(--outline-active-color);");
document.writeln("}");
document.writeln("");
document.writeln(".file-list-item.active {");
document.writeln("    border-left: 4px solid var(--drake-accent);");
document.writeln("}");
document.writeln("");
document.writeln("#md-searchpanel .btn:not(.close-btn):hover {");
document.writeln("    box-shadow: none;");
document.writeln("    background: var(--btn-hover-bg-color);");
document.writeln("}");
document.writeln("");
document.writeln("/*checkbox*/");
document.writeln("#write input[type=checkbox] {");
document.writeln("    opacity: 0;");
document.writeln("    height: 1.6rem;");
document.writeln("    width: 1.6rem;");
document.writeln("    margin-left: -2em;");
document.writeln("    margin-top: 0;");
document.writeln("    top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("#write .ul-list li.md-task-list-item.task-list-done::before {");
document.writeln("    content: \'\';");
document.writeln("    background: var(--checkbox-checked) 0 0 no-repeat;");
document.writeln("    background-size: 100%;");
document.writeln("    display: inline-block;");
document.writeln("    position: absolute;");
document.writeln("    height: 1.6rem;");
document.writeln("    width: 1.6rem;");
document.writeln("    margin-left: -2em;");
document.writeln("}");
document.writeln("#write .ul-list li.md-task-list-item.task-list-not-done::before {");
document.writeln("    content: \'\';");
document.writeln("    background: var(--checkbox-unchecked) 0 0 no-repeat;");
document.writeln("    background-size: 100%;");
document.writeln("    display: inline-block;");
document.writeln("    position: absolute;");
document.writeln("    height: 1.6rem;");
document.writeln("    width: 1.6rem;");
document.writeln("    margin-left: -2em;");
document.writeln("}");
document.writeln(".task-list-item p {");
document.writeln("    line-height: 1.6rem;");
document.writeln("}");
document.writeln("");
document.writeln("/*insert table*/");
document.writeln(".btn {");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln(".modal-content {");
document.writeln("    border-radius: 8px;");
document.writeln("}");
document.writeln("");
document.writeln(".btn-primary:hover, .btn-primary:active {");
document.writeln("    background-color: var(--btn-hover-bg-color);");
document.writeln("    color: var(--drake-highlight);");
document.writeln("}");
document.writeln("");
document.writeln(".btn-primary {");
document.writeln("    background-color: transparent;");
document.writeln("    color: var(--drake-highlight);");
document.writeln("}");
document.writeln("");
document.writeln(".btn-default {");
document.writeln("    background-color: transparent;");
document.writeln("}");
document.writeln("");
document.writeln(".btn:active {");
document.writeln("    box-shadow: none;");
document.writeln("    border-color: transparent;");
document.writeln("}");
document.writeln("");
document.writeln(".modal-footer {");
document.writeln("    border-top: none;");
document.writeln("}");
document.writeln("");
document.writeln("#table-insert-col, #table-insert-row {");
document.writeln("    background: var(--input-bg-color);");
document.writeln("    border-radius: 2px;");
document.writeln("}");
document.writeln("");
document.writeln("/*preference panel*/");
document.writeln("#megamenu-content {");
document.writeln("    background-image: none !important;");
document.writeln("    background-color: var(--bg-color);");
document.writeln("}");
document.writeln("#top-titlebar {");
document.writeln("    height: inherit;");
document.writeln("    background-color: var(--bg-color);");
document.writeln("}");
document.writeln("#megamenu-menu-sidebar {");
document.writeln("    background-color: var(--bg-color);");
document.writeln("    color: var(--text-color);");
document.writeln("}");
document.writeln(".long-btn {");
document.writeln("    width: inherit;");
document.writeln("    min-width: 300px;");
document.writeln("    border: 1px solid var(--text-color);");
document.writeln("    border-radius: 6px;");
document.writeln("}");
document.writeln(".megamenu-menu-panel h1 {");
document.writeln("    margin-bottom: 3rem;");
document.writeln("    text-align: left;");
document.writeln("}");
document.writeln(".megamenu-menu-panel h1, .megamenu-menu-panel h2 {");
document.writeln("    font-weight: normal;");
document.writeln("}");
document.writeln("#recent-file-panel-search-input {");
document.writeln("    height: 45px;");
document.writeln("    border: none;");
document.writeln("    border-bottom: 1px solid var(--text-color);");
document.writeln("    padding-left: 8px;");
document.writeln("}");
document.writeln("#recent-file-panel-search-input::placeholder {");
document.writeln("    color: var(--text-color);");
document.writeln("    opacity: .5;");
document.writeln("}");
document.writeln(".megamenu-menu-header {");
document.writeln("    border-bottom: none;");
document.writeln("}");
document.writeln("#recent-file-panel-action-btn {");
document.writeln("    background: none;");
document.writeln("    border: none;");
document.writeln("}");
document.writeln("#recent-file-panel-action-btn-container {");
document.writeln("    float: none;");
document.writeln("    display: inline-block;");
document.writeln("}");
document.writeln("#top-titlebar .toolbar-icon.btn.hover, #top-titlebar .toolbar-icon.btn:hover {");
document.writeln("    background-color: var(--btn-hover-bg-color);");
document.writeln("    color: var(--text-color);");
document.writeln("}");
document.writeln(".megamenu-menu-panel .btn:hover {");
document.writeln("    background-color: var(--btn-hover-bg-color) !important;");
document.writeln("    color: var(--text-color);");
document.writeln("}");
document.writeln("#recent-file-panel tbody tr:nth-child(2n-1),");
document.writeln(".megamenu-menu-panel table thead,");
document.writeln(".megamenu-menu-panel table tr {");
document.writeln("    background-color: transparent;");
document.writeln("}");
document.writeln(".megamenu-menu-panel table {");
document.writeln("    font-weight: normal;");
document.writeln("}");
document.writeln("#megamenu-back-btn {");
document.writeln("    color: var(--text-color);");
document.writeln("    border: 1px solid var(--text-color);");
document.writeln("}");
document.writeln(".megamenu-menu-header #megamenu-menu-header-title {");
document.writeln("    color: var(--text-color);");
document.writeln("}");
document.writeln("header, .context-menu, .megamenu-content, footer {");
document.writeln("    font-family: var(--text-font);");
document.writeln("}");
document.writeln(".ty-preferences select {");
document.writeln("    padding-left: 2px;");
document.writeln("}");
document.writeln(".preference-item-hint {");
document.writeln("    font-size: 14px;");
document.writeln("}");
document.writeln("a.ty-link {");
document.writeln("    color: var(--a-color);");
document.writeln("    margin: 0 .2rem;");
document.writeln("}");
document.writeln("");
document.writeln("/**");
document.writeln("    code render");
document.writeln("    Name: IntelliJ IDEA darcula theme");
document.writeln("    From IntelliJ IDEA by JetBrains");
document.writeln(" */");
document.writeln(".cm-s-inner.CodeMirror {");
document.writeln("    background: none;");
document.writeln("    color: var(--code-block-color);");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-meta {");
document.writeln("    color: #BBB529;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-number {");
document.writeln("    color: #6897BB;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-keyword {");
document.writeln("    color: #CC7832;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-def {");
document.writeln("    color: #FFD760;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-variable {");
document.writeln("    color: #A9B7C6;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-variable-2 {");
document.writeln("    color: #A9B7C6;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-variable-3 {");
document.writeln("    color: #9876AA;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-type {");
document.writeln("    color: #AABBCC;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-property {");
document.writeln("    color: #FFC66D;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-operator {");
document.writeln("    color: #A9B7C6;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-string {");
document.writeln("    color: #6A8759;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-string-2 {");
document.writeln("    color: #6A8759;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-comment {");
document.writeln("    color: #787878;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-link {");
document.writeln("    color: #CC7832;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-atom {");
document.writeln("    color: #CC7832;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-error {");
document.writeln("    color: #BC3F3C;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-tag {");
document.writeln("    color: #E8BF6A;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-quote {");
document.writeln("    color: #a6e22e;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-attribute {");
document.writeln("    color: #9876AA;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-qualifier {");
document.writeln("    color: #6A8759;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-bracket {");
document.writeln("    color: #E8BF6A;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-builtin {");
document.writeln("    color: #FF9E59;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-special {");
document.writeln("    color: #FF9E59;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-matchhighlight {");
document.writeln("    color: #FFFFFF;");
document.writeln("    background-color: rgba(50, 89, 48, .7);");
document.writeln("    font-weight: normal;");
document.writeln("}");
document.writeln(".cm-s-inner span.cm-searching {");
document.writeln("    color: #FFFFFF;");
document.writeln("    background-color: rgba(61, 115, 59, .7);");
document.writeln("    font-weight: normal;");
document.writeln("}");
document.writeln(".cm-s-inner .CodeMirror-gutters {");
document.writeln("    border-right: none;");
document.writeln("    border-radius: 2px;");
document.writeln("    padding-left: 0.5rem;");
document.writeln("    background: var(--bg-color);");
document.writeln("}");
document.writeln(".cm-s-inner .CodeMirror-linenumber {");
document.writeln("    color: #787878;");
document.writeln("}");
document.writeln(".cm-s-inner .CodeMirror-matchingbracket {");
document.writeln("    background-color: #3B514D;");
document.writeln("    color: #FFEF28 !important;");
document.writeln("}");
document.writeln(".cm-s-inner .CodeMirror-selected {");
document.writeln("    background: #214283 !important;");
document.writeln("}");
document.writeln(".cm-s-inner .CodeMirror-selectedtext {");
document.writeln("    background: #214283 !important;");
document.writeln("}");
document.writeln(".cm-s-typora-default .CodeMirror-selectedtext {");
document.writeln("    background: var(--select-text-bg-color) !important;");
document.writeln("}");
document.writeln(".cm-overlay.CodeMirror-selectedtext {");
document.writeln("    background: var(--select-text-bg-color) !important;");
document.writeln("}");
document.writeln(".cm-s-inner div.CodeMirror-cursor {");
document.writeln("    border-left: 1px solid var(--code-block-color);");
document.writeln("}");
document.writeln(".cm-s-inner .cm-header, .cm-s-inner.cm-header {");
document.writeln("    color: #FFD760;");
document.writeln("    font-weight: normal;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("</style><title>紧张刺激的卡牌游戏</title>");
document.writeln("</head>");
document.writeln("<body class=\'typora-export os-windows\'><div class=\'typora-export-content\'>");
document.writeln("<div id=\'write\'  class=\'\'><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><h1 id=\'紧张刺激的卡牌游戏\'><span>紧张刺激的卡牌游戏</span></h1><h2 id=\'🎉-welcome-to-my-game\'><span>🎉 Welcome to My game! </span></h2><p><font size = 4 color = DarkTurquoise><span>	</span><span>It&#39;s a little game about line algebra (</span><del><span>a crude product of coping with a teacher&#39;s big assignment</span></del><span>),The rules are as follows:</span></font></p><ol start=\'\' ><li><p><font size = 3 ><span>There are two or more players playing at the same time</span></font><span>	</span></p></li><li><p><font size = 3 ><span>Whoever plays the last card so that the matrix becomes a RREF matrix loses.</span></font></p></li><li><p><font size = 3 ><span>There are three types of cards: addition, multiplication, and exchange operations</span></font><span>.</span></p></li></ol><p>&nbsp;</p><p>&nbsp;</p><p><font size = 6 color = Red><span>!Warning:</span></font></p><p>&nbsp;</p><p><font size = 4 ><span>	</span><span>The login system for this product is an unprotected database storage written by the author himself. To prevent others from viewing it maliciously, do not use your account password from elsewhere.</span></font></p><p>&nbsp;</p><p><img src=\'https://img.shields.io/badge/Elemental-Line Algebra-Chartreuse\' referrerpolicy=\'no-referrer\' alt=\'Static Badge\'><span>  </span><img src=\'https://img.shields.io/badge/Elemental-Game Theory-Chartreuse\' referrerpolicy=\'no-referrer\' alt=\'Static Badge\'><span> </span></p><p><img src=\'https://img.shields.io/badge/Python-blue\' referrerpolicy=\'no-referrer\' alt=\'Static Badge\'><span> </span><img src=\'https://img.shields.io/badge/HTML-blue\' referrerpolicy=\'no-referrer\' alt=\'Static Badge\'><span> </span><img src=\'https://img.shields.io/badge/JavaScript-blue\' referrerpolicy=\'no-referrer\' alt=\'Static Badge\'><span> </span><img src=\'https://img.shields.io/badge/DataBase-blue\' referrerpolicy=\'no-referrer\' alt=\'Static Badge\'><span> </span></p><p>&nbsp;</p></div></div>");
document.writeln("</body>");
document.writeln("</html>");